### ISSUE TITLE
Problems with intl and flutter 3.22.1

### ISSUE THREAD

**Issue by Thibault4** [channdara/flutter_localization#19]
New flutter version 3.22.1 conflict with intl version

Error : 

```
Note: intl is pinned to version 0.19.0 by flutter_localizations from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.


Because x depends on flutter_localizations from sdk which depends on intl 0.19.0, intl 0.19.0 is required.
So, because x depends on intl ^0.18.1, version solving failed.
```

My pubspec.yaml 

```
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+7

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  http: ^0.13.3
  google_maps_flutter: ^2.0.1
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.17.9
  shared_preferences: ^2.0.6
  enum_to_string: ^2.0.1
  dotted_line: ^3.0.0
  image_picker: ^1.1.1
  flutter_rating_bar: ^4.0.0
  photo_view: ^0.15.0
  firebase_storage: ^11.2.0
  uuid: ^3.0.6
  lottie: ^3.0.0
  carousel_slider: ^4.0.0
  url_launcher: ^6.0.9
  rxdart: ^0.27.2
  firebase_messaging: ^14.6.0
  fl_chart: ^0.68.0
  sliding_up_panel: ^2.0.0+1
  badges: ^3.0.2
  flutter_local_notifications: ^17.1.2
  dio: ^5.0.1
  qr_flutter: ^4.0.0
  easy_localization: ^3.0.0
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  path_provider: ^2.0.9
  fluttertoast: ^8.2.4
  dropdown_button2: ^2.0.0
  sign_in_with_apple: ^6.1.0
  percent_indicator: ^4.0.0
  giphy_picker: ^3.0.1
  flutter_stripe: ^10.0.0
  file_picker: ^8.0.3
  universal_io: ^2.0.4
  gallery_saver: ^2.3.2
  flutter_translate: ^4.0.4
  animated_toggle_switch: ^0.8.2
  chewie: ^1.3.5
  image_editor_plus: ^0.2.0
  flutter_slidable: ^3.0.1
  video_thumbnail: ^0.5.3
  video_editor: ^3.0.0
  video_player: ^2.4.7
  video_compress: ^3.1.1
  flutter_image_compress: ^2.2.0
  qr_code_scanner: ^1.0.1
  dismissible_page: ^1.0.1
  appinio_swiper: ^2.0.1
  geolocator: ^12.0.0
  firebase_core_platform_interface: ^5.0.0
  image_painter: ^0.7.1
  camera: ^0.11.0
  darq: ^2.0.0
  accordion: ^2.5.1
  dart_ipify: ^1.1.1
  device_info_plus: ^10.1.0
  camera_web: ^0.3.1+1
  shared_preferences_web: ^2.0.4
  google_maps_flutter_web: ^0.5.7
  stop_watch_timer: ^3.1.1
  map_launcher: ^3.3.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.5
  audio_waveforms: ^1.0.3
  just_audio: ^0.9.31
  external_app_launcher: ^4.0.0
  go_router: ^14.1.3
  encrypt: ^5.0.1
  latlong2: ^0.8.1
  flutter_map: ^4.0.0
  facebook_audience_network: ^1.0.1
  any_link_preview: ^3.0.0
  popover: ^0.3.0+1
  flutter_vibrate: ^1.3.0
  geoflutterfire2: ^2.3.15
  intl_phone_number_input: ^0.7.3+1
  crypto: ^3.0.3
  intl: ^0.18.1
  image_downloader_web: ^2.0.2
  audioplayers: ^6.0.0
  url_strategy: ^0.2.0
  spotify: ^0.11.0
  package_info_plus: ^8.0.0
  flutter_lints: ^4.0.0
  collection: ^1.17.1
  firebase_core: ^2.17.0
  syncfusion_flutter_charts: ^25.2.5
  anchor_scroll_controller: ^0.4.4
  flex_color_picker: ^3.3.0
  hexcolor: ^3.0.1
  sliding_up_panel2: ^3.3.0+1
  syncfusion_flutter_core: ^25.2.5
  selectable: ^0.3.0
  flutter_bounceable: ^1.1.0
  meta: ^1.9.1
  emoji_picker_flutter: ^2.2.0
  photo_gallery: ^2.1.1
  permission_handler: ^11.1.0
  transparent_image: ^2.0.1
  app_links: ^6.1.1
  share_plus: ^9.0.0
  flutter_stripe_web: ^5.0.0
  location: ^6.0.2
  webview_flutter: ^4.7.0
  swipeable_page_route: ^0.4.2
  toastification: ^1.0.0
  sentry_flutter: ^8.2.0
  flutter_map_marker_cluster: ^1.1.0
  hyper_effects: ^0.2.3
  skeletonizer: ^1.1.2+1
  voice_message_package: ^2.1.4
  super_annotations: ^0.8.1
  pdf: ^3.10.8
  ffmpeg_kit_flutter: ^6.0.3
  crop_image: ^1.0.12

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  image_path: "assets/icons/logo_1024x1024.png" 
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/social_network/
    - assets/auth/
    - assets/i18n/
dev_dependencies:
  dart_code_metrics: ^5.0.1
  fake_cloud_firestore: ^2.4.1+1
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  test: ^1.24.9
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

Flutter doctor : 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.1, on macOS 14.4.1 23E224 darwin-arm64, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.85.2)
```
